/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendavirtual;

import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author AYUSO
 */
public class ListaDeProductos extends javax.swing.JFrame {

    /**
     * Creates new form ListaDeProductos
     */
    
    DatosUsuario oDatosUsuario;
    
    private ResultSet rs, rt;
    private Connection conexion;
     String id;
    public ListaDeProductos() {
        initComponents();
        this.getContentPane().setBackground(Color.ORANGE);
        setTitle("Lista de mis Productos");
        setLocationRelativeTo(null);
        URL url = getClass().getResource("icono.png");
        ImageIcon icono = new ImageIcon( url );
        setIconImage(icono.getImage()); 
        oDatosUsuario = DatosUsuario.getDatosUsuario();
        jLabel1.setText(oDatosUsuario.getNombre());
        jTextNombreProducto.setEditable(false);
        jTextCategoria.setEditable(false);
        jTextDescripcion.setEditable(false);
        this.setSize(500, 500);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection ("jdbc:mysql://localhost:3306/virtualtienda?zeroDateTimeBehavior=convertToNull","root", "");
            Statement s = conexion.createStatement();
            rs = s.executeQuery ("SELECT p.Nombre_producto, c.Nombre_categoria, c.idCategoria, p.Descripcion, p.idProducto  FROM producto p, usuario u, categoria c WHERE p.idUsuario = u.idUsuario and c.idCategoria = p.idCategoria and p.idUsuario ="+oDatosUsuario.getIdUsuario());
            //ResultSet rst = s.executeQuery("");
            
            int fin;
            rs.last();
            fin = rs.getRow();
            if (fin!=0) {
                rs.first();
                jTextNombreProducto.setText(rs.getString(1));
                jTextCategoria.setText(rs.getString(2));
                jTextDescripcion.setText(rs.getString(4));                
            } 
                //System.out.println (rs.getInt (1) + " " + rs.getString (2)+ " ");     
            
            //rs.close();
            //conexion.close();
        } catch (ClassNotFoundException | SQLException e)
        {
        }   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuario = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        jTextNombreProducto = new javax.swing.JTextField();
        jTextCategoria = new javax.swing.JTextField();
        Siguiente = new javax.swing.JButton();
        Anteriror = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDescripcion = new javax.swing.JTextArea();
        Beliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de mis Articulos");

        Usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Usuario.setText("Usuario:");

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nombre.setText("Nombre Producto:");

        Categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Categoria.setText("Categoria:");

        Descripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Descripcion.setText("Descripcion:");

        jTextNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreProductoActionPerformed(evt);
            }
        });

        Siguiente.setBackground(new java.awt.Color(0, 153, 153));
        Siguiente.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Siguiente.setText("Siguiente>>");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        Anteriror.setBackground(new java.awt.Color(0, 153, 153));
        Anteriror.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Anteriror.setText("<<Anterior");
        Anteriror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnterirorActionPerformed(evt);
            }
        });

        Regresar.setBackground(new java.awt.Color(0, 153, 153));
        Regresar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextDescripcion.setColumns(20);
        jTextDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextDescripcion);

        Beliminar.setBackground(new java.awt.Color(0, 153, 153));
        Beliminar.setText("Eliminar");
        Beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre)
                    .addComponent(Categoria)
                    .addComponent(Descripcion)
                    .addComponent(Usuario))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(jTextCategoria)
                            .addComponent(jTextNombreProducto)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Beliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Anteriror)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(jTextNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Categoria)
                    .addComponent(jTextCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Siguiente)
                    .addComponent(Anteriror))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regresar)
                    .addComponent(Beliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        try {
            
            if(rs.next()){
                jTextNombreProducto.setText(rs.getString(1));
                jTextCategoria.setText(rs.getString(2));
                jTextDescripcion.setText(rs.getString(4)); 
            }
            else
                rs.last();
                
            
        } catch (SQLException ex) {
            Logger.getLogger(ListaDeProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }//GEN-LAST:event_SiguienteActionPerformed

    private void AnterirorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnterirorActionPerformed
        // TODO add your handling code here:
        
       try {
            
            if(rs.previous()){
                jTextNombreProducto.setText(rs.getString(1));
                jTextCategoria.setText(rs.getString(2));
                jTextDescripcion.setText(rs.getString(4)); 
            }
            else
                rs.first();
                
            
        } catch (SQLException ex) {
            Logger.getLogger(ListaDeProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AnterirorActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        try { 
            conexion.close();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(ListaDeProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
         
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarActionPerformed

    private void BeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminarActionPerformed
         int opc;
        Icon icono = new ImageIcon(getClass().getResource("baratero3.gif"));
         opc=JOptionPane.showOptionDialog(null, "Esta seguro que desea Eliminar el producto" ,null , WIDTH, WIDTH, icono,new Object[]{"SI" , "N0"} , null);
         if(opc==0){
             try {
         Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection ("jdbc:mysql://localhost:3306/virtualtienda?zeroDateTimeBehavior=convertToNull","root", "");
           Statement s = conexion.createStatement();
            id = rs.getString(5);
            System.out.println(id);
           int a= s.executeUpdate("DELETE FROM `virtualtienda`.`producto` WHERE `producto`.`idProducto` = "+id);
           JOptionPane.showMessageDialog(null, "Se a eliminado correctamente el producto",null,WIDTH);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ListaDeProductos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Elimine primero la oferta del producto",null,JOptionPane.ERROR_MESSAGE);             
        }        
        this.setVisible(false);
         }
    }//GEN-LAST:event_BeliminarActionPerformed

    private void jTextNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ListaDeProductos().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anteriror;
    private javax.swing.JButton Beliminar;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCategoria;
    private javax.swing.JTextArea jTextDescripcion;
    private javax.swing.JTextField jTextNombreProducto;
    // End of variables declaration//GEN-END:variables
}
