/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendavirtual;

import java.awt.Color;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class Comprar extends javax.swing.JFrame {

    /**
     * Creates new form Comprar
     */
    DatosUsuario oDatosUsuario;
    Connection conexion;
    ResultSet rs;
    
   
    public Comprar() {
        initComponents();
        this.getContentPane().setBackground(Color.ORANGE);
        setTitle("Comprar producto");
        
        setLocationRelativeTo(null);
        URL url = getClass().getResource("icono.png");
        ImageIcon icono = new ImageIcon( url );
        setIconImage(icono.getImage()); 
        oDatosUsuario = DatosUsuario.getDatosUsuario();
        jLabel1.setText(oDatosUsuario.getNombre());
        
        this.setSize(700, 740);
        textVendedor.setEditable(false);
        textidOferta.setEditable(false);
        textCategoria.setEditable(false);
        textDisponibles.setEditable(false);
        textEstado.setEditable(false);
        textProducto.setEditable(false);
        textPrecio.setEditable(false);
        textUbicacion.setEditable(false);
        textDisponibles.setEditable(false);
        TextDescr.setEditable(false);
        textemail.setEditable(false);
        textCostoEnvio.setEditable(false);
        textTotal.setEditable(false);
        
        Numcuenta.setVisible(false);
        textNumCuenta.setVisible(false);
        banco.setVisible(false);
        textBanco.setVisible(false);
        jLabelFecha.setText(FechaActual());
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection ("jdbc:mysql://localhost:3306/virtualtienda?zeroDateTimeBehavior=convertToNull","root", "");
            Statement s = conexion.createStatement();
            Statement t = conexion.createStatement();
            rs = s.executeQuery ("SELECT o.idOfertas, u.Nombre, u.e_mail, c.Nombre_categoria, "
                                    + "p.Nombre_producto, e.Nombre_entidad, o.Estado, o.precio, "
                                    + "o.cantidad, p.Descripcion, o.Descripcion " 
                                    +"FROM usuario u, producto p, categoria c, ofertas o, entidad e " 
                                    +"WHERE u.idUsuario = o.Usuario_vende " 
                                    +"and p.idProducto = o.idProducto " 
                                    +"and p.idCategoria = c.idCategoria "
                                    +"and e.idEntidad = u.idEntidad ");
         
            
            
            
           
            
            int fin;
            rs.last();
            fin = rs.getRow();
            if (fin!=0) {
                rs.first();
                
                textidOferta.setText(rs.getString(1));
                textVendedor.setText(rs.getString(2));
                textemail.setText(rs.getString(3));
                textCategoria.setText(rs.getString(4));
                textProducto.setText(rs.getString(5));
                textUbicacion.setText(rs.getString(6));
                textEstado.setText(rs.getString(7));
                textPrecio.setText(rs.getString(8));
                textDisponibles.setText(rs.getString(9));
                TextDescr.setText(rs.getString(10)+" "+rs.getString(11));
               
                
            } 
           
            
            
        } catch (ClassNotFoundException | SQLException e)
        {
            e.printStackTrace();
        }   
       
    }
    public String FechaActual(){
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY-MM-dd");
        return formatofecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuario = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Idoferta = new javax.swing.JLabel();
        Producto = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Lugar = new javax.swing.JLabel();
        Pago = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Numcuenta = new javax.swing.JLabel();
        banco = new javax.swing.JLabel();
        Pagos = new javax.swing.JComboBox();
        Guardardatos = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        textVendedor = new javax.swing.JTextField();
        textidOferta = new javax.swing.JTextField();
        textCategoria = new javax.swing.JTextField();
        textPrecio = new javax.swing.JTextField();
        textEstado = new javax.swing.JTextField();
        textemail = new javax.swing.JTextField();
        textUbicacion = new javax.swing.JTextField();
        textNumCuenta = new javax.swing.JTextField();
        textBanco = new javax.swing.JTextField();
        textProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Envio = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextDescr = new javax.swing.JTextArea();
        textDisponibles = new javax.swing.JTextField();
        Anterior = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textCostoEnvio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textTotal = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSpinner1 = new javax.swing.JSpinner();
        Calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Usuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Usuario.setText("Usuario:");

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nombre.setText("Vendedor:");

        Idoferta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Idoferta.setText("Id Oferta:");

        Producto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Producto.setText("Producto:");

        Categoria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Categoria.setText("Categoria:");

        Estado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Estado.setText("Estado:");

        Precio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Precio.setText("Precio:");

        Cantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cantidad.setText("Disponibles");

        Descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Descripcion.setText("Descripcion:");

        Email.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Email.setText("E-mail:");

        Lugar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Lugar.setText("Ubicacion:");

        Pago.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Pago.setText("Forma de Pago:");

        Fecha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fecha.setText("Fecha de Compra:");

        Numcuenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Numcuenta.setText("Num. de Cuenta:");

        banco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        banco.setText("Banco:");

        Pagos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efectivo", "Tarjeta de Credito" }));
        Pagos.setToolTipText("");
        Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagosActionPerformed(evt);
            }
        });

        Guardardatos.setBackground(new java.awt.Color(0, 153, 153));
        Guardardatos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Guardardatos.setText("Realizar Compra");
        Guardardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardardatosActionPerformed(evt);
            }
        });

        Regresar.setBackground(new java.awt.Color(0, 153, 153));
        Regresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        Envio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Envio.setText("Envio:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente Recoge", "Entrega a Domicilio" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        TextDescr.setColumns(20);
        TextDescr.setRows(5);
        jScrollPane1.setViewportView(TextDescr);

        Anterior.setBackground(new java.awt.Color(0, 153, 153));
        Anterior.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Anterior.setText("<<Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });

        Siguiente.setBackground(new java.awt.Color(0, 153, 153));
        Siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Siguiente.setText("Siguiente>>");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Compra");

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Costo Envio:");

        textCostoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCostoEnvioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Total: $");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        Calcular.setBackground(new java.awt.Color(0, 153, 153));
        Calcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Descripcion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lugar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(Estado))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(textEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(Categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addComponent(Precio))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                    .addComponent(textVendedor, javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                                        .addComponent(textCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(Usuario)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(26, 26, 26)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Producto)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(textProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Cantidad)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(textDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(Email)
                                                                .addGap(39, 39, 39)
                                                                .addComponent(textemail))))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(27, 27, 27)
                                                        .addComponent(Idoferta)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(textidOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(53, 53, 53)))
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(Anterior)
                        .addGap(114, 114, 114)
                        .addComponent(Siguiente)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Guardardatos)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Numcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(Pago))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Pagos, 0, 127, Short.MAX_VALUE)
                                    .addComponent(textTotal))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(banco, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textBanco))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(Regresar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(Envio))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, 0, 167, Short.MAX_VALUE)
                                            .addComponent(textCostoEnvio))))))
                        .addGap(94, 94, 94))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Usuario)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Idoferta)
                                        .addComponent(textidOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textemail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Nombre)
                                .addComponent(textVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Email)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Categoria)
                            .addComponent(Producto))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estado)
                            .addComponent(Lugar)
                            .addComponent(textEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Precio)
                                .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Cantidad)))
                    .addComponent(textDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anterior)
                    .addComponent(Siguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Envio)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pago)
                    .addComponent(Pagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(textCostoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calcular))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numcuenta)
                    .addComponent(banco)
                    .addComponent(textBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Guardardatos)
                    .addComponent(Regresar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        try { 
            rs.close();
            conexion.close();
        } catch (SQLException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_RegresarActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        try {
            // TODO add your handling code here:
            if(rs.previous()){
                textidOferta.setText(rs.getString(1));
                textVendedor.setText(rs.getString(2));
                textemail.setText(rs.getString(3));
                textCategoria.setText(rs.getString(4));
                textProducto.setText(rs.getString(5));
                textUbicacion.setText(rs.getString(6));
                textEstado.setText(rs.getString(7));
                textPrecio.setText(rs.getString(8));
                textDisponibles.setText(rs.getString(9));
                TextDescr.setText(rs.getString(10)+" "+rs.getString(11));
                
            }
            else
                rs.first();
                
            
        } catch (SQLException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AnteriorActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        try {
            // TODO add your handling code here:
            if(rs.next()){
                textidOferta.setText(rs.getString(1));
                textVendedor.setText(rs.getString(2));
                textemail.setText(rs.getString(3));
                textCategoria.setText(rs.getString(4));
                textProducto.setText(rs.getString(5));
                textUbicacion.setText(rs.getString(6));
                textEstado.setText(rs.getString(7));
                textPrecio.setText(rs.getString(8));
                textDisponibles.setText(rs.getString(9));
                TextDescr.setText(rs.getString(10)+" "+rs.getString(11));
            }
            else
                rs.last();
        } catch (SQLException ex) {
            Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SiguienteActionPerformed

    private void PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagosActionPerformed
        // TODO add your handling code here:
       
        if(Pagos.getSelectedIndex() == 0){
            Numcuenta.setVisible(false);
            textNumCuenta.setVisible(false);
            banco.setVisible(false);
            textBanco.setVisible(false);
            
        }
        else {
            Numcuenta.setVisible(true);
            textNumCuenta.setVisible(true);
            banco.setVisible(true);
            textBanco.setVisible(true);
        }
            
        
    }//GEN-LAST:event_PagosActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
          
                if(jComboBox1.getSelectedIndex() == 0) {                    
                    textCostoEnvio.setText("0");
                }
                else {                   
                    textCostoEnvio.setText("100");
                }
      
        
            
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        int costoEnvio = 0;
        float precio = 0;
        int cantidad = 0;
        
        costoEnvio = Integer.parseInt(textCostoEnvio.getText());
        cantidad = (int)jSpinner1.getValue();
        precio = Float.parseFloat(textPrecio.getText());
        float total = cantidad*precio+costoEnvio;
        textTotal.setText(""+total);
    }//GEN-LAST:event_CalcularActionPerformed

    private void textCostoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCostoEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCostoEnvioActionPerformed

    private void GuardardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardardatosActionPerformed
        // TODO add your handling code here:
         oDatosUsuario = DatosUsuario.getDatosUsuario();
         Icon icono = new ImageIcon(getClass().getResource("baratero3.gif"));
         
        float CostoCompra = Float.parseFloat(textPrecio.getText())*(int)jSpinner1.getValue();
        int idEnvio = jComboBox1.getSelectedIndex()+1;
        int opc;
         opc=JOptionPane.showOptionDialog(null, "¿Esta seguro que desea Comprar el Producto?" ,null , WIDTH, WIDTH, icono,new Object[]{"SI" , "N0"} , null);
         if (opc==0) {
            try
            {
               Class.forName("com.mysql.jdbc.Driver");
               //conexion = DriverManager.getConnection ("jdbc:mysql://localhost:3306/virtualtienda?zeroDateTimeBehavior=convertToNull","root", "");
               Statement s = conexion.createStatement();
                             
                  s.execute("INSERT INTO compras(idCompras, idOfertas, Usuario_compra, Forma_pago, Fecha, idEnvio, Cantidad, Precio_Total_compra, Precio_comp_envio) "
                           + "VALUES(NULL,"+textidOferta.getText()+","+oDatosUsuario.getIdUsuario()+",'"
                           +Pagos.getSelectedItem()+"','"+jLabelFecha.getText()+"',"+idEnvio
                           +","+jSpinner1.getValue()+","+CostoCompra+","+textTotal.getText()+")");
                   JOptionPane.showMessageDialog(this, "Datos ingresados correctamente");
                   dispose();
               if(Pagos.getSelectedItem()=="Tarjeta de Credito"){
                   s.execute("INSERT INTO datos_bancarios_usuario(banco,idUsuario,Numero_cuenta,observaciones) "
                           + "VALUES('"+textBanco.getText()+"',"+oDatosUsuario.getIdUsuario()+",'"+textNumCuenta.getText()+"','ninguna')");
               }             
                 
               
            } catch (ClassNotFoundException | SQLException e)
            {
               e.printStackTrace();
            }
         }  
    }//GEN-LAST:event_GuardardatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Envio;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel Fecha;
    private javax.swing.JButton Guardardatos;
    private javax.swing.JLabel Idoferta;
    private javax.swing.JLabel Lugar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Numcuenta;
    private javax.swing.JLabel Pago;
    private javax.swing.JComboBox Pagos;
    private javax.swing.JLabel Precio;
    private javax.swing.JLabel Producto;
    private javax.swing.JButton Regresar;
    private javax.swing.JButton Siguiente;
    private javax.swing.JTextArea TextDescr;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel banco;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField textBanco;
    private javax.swing.JTextField textCategoria;
    private javax.swing.JTextField textCostoEnvio;
    private javax.swing.JTextField textDisponibles;
    private javax.swing.JTextField textEstado;
    private javax.swing.JTextField textNumCuenta;
    private javax.swing.JTextField textPrecio;
    private javax.swing.JTextField textProducto;
    private javax.swing.JTextField textTotal;
    private javax.swing.JTextField textUbicacion;
    private javax.swing.JTextField textVendedor;
    private javax.swing.JTextField textemail;
    private javax.swing.JTextField textidOferta;
    // End of variables declaration//GEN-END:variables
}
