/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendavirtual;

import java.awt.Color;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Icon;
import tiendavirtual.AgregarOferta;
import tiendavirtual.AgregarProducto;
import tiendavirtual.Comprar;
import tiendavirtual.ListaDeOfertas;
import tiendavirtual.ListaDeProductos;

/**
 *
 * @author AYUSO
 */
public class IngresaMercadoLibre extends javax.swing.JFrame {
 DatosUsuario oDatosUsuario;
   
    
    /**
     * Creates new form IngresaMercadoLibre
     */
    public IngresaMercadoLibre() {
        
        initComponents();
        setTitle("Bienvenido a su Cuenta");
        setLocationRelativeTo(null);
        URL url = getClass().getResource("icono.png");
        ImageIcon icono = new ImageIcon( url );
        setIconImage(icono.getImage()); 
        oDatosUsuario = DatosUsuario.getDatosUsuario();
        this.getContentPane().setBackground(Color.ORANGE);
        this.setSize(450, 400);
       //jLabel1.setText(oDatosUsuario.getNombre());
        
       // jLabel1.setText(oDatosUsuario.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuComprar = new javax.swing.JMenu();
        ComprarArticulo = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        CerrarSesionComprar = new javax.swing.JMenuItem();
        SalirComprar = new javax.swing.JMenuItem();
        MenuVender = new javax.swing.JMenu();
        AgregarArticulo = new javax.swing.JMenuItem();
        AgregarOferta = new javax.swing.JMenuItem();
        Verlistademisart = new javax.swing.JMenuItem();
        Verlstademisofer = new javax.swing.JMenuItem();
        CerrarSesiVender = new javax.swing.JMenuItem();
        SalirVender = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido");

        jLabel1.setBackground(new java.awt.Color(51, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido");

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Encuentra todo lo que buscabas!!! ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendavirtual/baratero3.gif"))); // NOI18N

        MenuComprar.setText("Comprar");
        MenuComprar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ComprarArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComprarArticulo.setText("ComprarArticulo");
        ComprarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarArticuloActionPerformed(evt);
            }
        });
        MenuComprar.add(ComprarArticulo);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("Buscar Artículo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuComprar.add(jMenuItem1);

        CerrarSesionComprar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CerrarSesionComprar.setText("Cerrar Sesion");
        CerrarSesionComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionComprarActionPerformed(evt);
            }
        });
        MenuComprar.add(CerrarSesionComprar);

        SalirComprar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SalirComprar.setText("Salir");
        SalirComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirComprarActionPerformed(evt);
            }
        });
        MenuComprar.add(SalirComprar);

        jMenuBar1.add(MenuComprar);

        MenuVender.setText("Vender");
        MenuVender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        AgregarArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarArticulo.setText("Agregar Articulo");
        AgregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarArticuloActionPerformed(evt);
            }
        });
        MenuVender.add(AgregarArticulo);

        AgregarOferta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarOferta.setText("Agregar Oferta");
        AgregarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarOfertaActionPerformed(evt);
            }
        });
        MenuVender.add(AgregarOferta);

        Verlistademisart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Verlistademisart.setText("Ver Lista de mis articulos");
        Verlistademisart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerlistademisartActionPerformed(evt);
            }
        });
        MenuVender.add(Verlistademisart);

        Verlstademisofer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Verlstademisofer.setText("Ver Lista de mis ofertas");
        Verlstademisofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerlstademisoferActionPerformed(evt);
            }
        });
        MenuVender.add(Verlstademisofer);

        CerrarSesiVender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CerrarSesiVender.setText("Cerrar Sesion");
        CerrarSesiVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesiVenderActionPerformed(evt);
            }
        });
        MenuVender.add(CerrarSesiVender);

        SalirVender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SalirVender.setText("Salir");
        SalirVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirVenderActionPerformed(evt);
            }
        });
        MenuVender.add(SalirVender);

        jMenuBar1.add(MenuVender);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComprarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarArticuloActionPerformed
        // TODO add your handling code here:
        Comprar objeto03 = new Comprar();
        objeto03.setVisible(true);
    }//GEN-LAST:event_ComprarArticuloActionPerformed

    private void AgregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarArticuloActionPerformed
        // TODO add your handling code here:
        AgregarProducto objeto04 = new AgregarProducto();
        objeto04.setVisible(true);
    }//GEN-LAST:event_AgregarArticuloActionPerformed

    private void CerrarSesionComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionComprarActionPerformed
        // TODO add your handling code here:
         int opc;
         opc=JOptionPane.showOptionDialog(null, "¿Esta seguro que desea Cerrar sesion?" ,null , WIDTH, WIDTH, null,new Object[]{"SI" , "N0"} , null);
         if(opc==0){
            this.dispose();
         }
         Principal.mostrarnew();
        // Principal.regresa();
    }//GEN-LAST:event_CerrarSesionComprarActionPerformed

    private void SalirComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirComprarActionPerformed
        // TODO add your handling code here:
        int opc;
         opc=JOptionPane.showOptionDialog(null, "Esta seguro que desea abandonar la página" ,null , WIDTH, WIDTH, null,new Object[]{"SI" , "N0"} , null);
         if(opc==0){
            System.exit(0);
         }
    }//GEN-LAST:event_SalirComprarActionPerformed

    private void AgregarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarOfertaActionPerformed
        // TODO add your handling code here:
        AgregarOferta objeto05 = new AgregarOferta();
        objeto05.setVisible(true);
    }//GEN-LAST:event_AgregarOfertaActionPerformed

    private void VerlistademisartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerlistademisartActionPerformed
        // TODO add your handling code here:
        ListaDeProductos objeto06 = new ListaDeProductos();
        objeto06.setVisible(true);
    }//GEN-LAST:event_VerlistademisartActionPerformed

    private void VerlstademisoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerlstademisoferActionPerformed

        // TODO add your handling code here:
      ListaDeOfertas objeto07 = new ListaDeOfertas();
      objeto07.setVisible(true);
    }//GEN-LAST:event_VerlstademisoferActionPerformed

    private void CerrarSesiVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesiVenderActionPerformed
        // TODO add your handling code here:
          int opc;
         opc=JOptionPane.showOptionDialog(null, "¿Esta seguro que desea Cerrar sesion?" ,null , WIDTH, WIDTH, null,new Object[]{"SI" , "N0"} , null);
         if(opc==0){
            this.dispose();
         }
    }//GEN-LAST:event_CerrarSesiVenderActionPerformed

    private void SalirVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirVenderActionPerformed
        // TODO add your handling code here:
         int opc;
         opc=JOptionPane.showOptionDialog(null, "Esta seguro que desea abandonar la página" ,null , WIDTH, WIDTH, null,new Object[]{"SI" , "N0"} , null);
         if(opc==0){
            System.exit(0);
         }
    }//GEN-LAST:event_SalirVenderActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        BuscarArticulo objeto08 = null;
     try {
         objeto08 = new BuscarArticulo();
     } catch (SQLException | IOException ex) {
         Logger.getLogger(IngresaMercadoLibre.class.getName()).log(Level.SEVERE, null, ex);
     }
        objeto08.setVisible(true);
        objeto08.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresaMercadoLibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresaMercadoLibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresaMercadoLibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresaMercadoLibre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new IngresaMercadoLibre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarArticulo;
    private javax.swing.JMenuItem AgregarOferta;
    private javax.swing.JMenuItem CerrarSesiVender;
    private javax.swing.JMenuItem CerrarSesionComprar;
    private javax.swing.JMenuItem ComprarArticulo;
    private javax.swing.JMenu MenuComprar;
    private javax.swing.JMenu MenuVender;
    private javax.swing.JMenuItem SalirComprar;
    private javax.swing.JMenuItem SalirVender;
    private javax.swing.JMenuItem Verlistademisart;
    private javax.swing.JMenuItem Verlstademisofer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
