/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiendavirtual;

import java.awt.Color;
import java.awt.Image;
import static java.awt.image.ImageObserver.WIDTH;
import java.net.URL;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author AYUSO
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    
    Inscribete objeto1= new Inscribete();
    
    /**
     * Creates new form PaginaPrincipal
     */
    public PaginaPrincipal() {
        
        ImageIcon imagen;
        
        initComponents();
        //URL url1 = getClass().getResource("fondo.jpg");
        //imagen = new ImageIcon (url1);
        //setIconImage(imagen.getImage()); 
        //setTitle("Pagina Principal");
        //this.getContentPane().setBackground(Color.CYAN);
        this.setLocationRelativeTo(null);
        URL url = getClass().getResource("icono.png");
        ImageIcon icono = new ImageIcon( url );
        setIconImage(icono.getImage()); 
         
       
        
        
        this.setSize(500, 500);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        Contrasena = new javax.swing.JLabel();
        Ingresa = new javax.swing.JButton();
        Inscribete = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagina Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Ventana1"); // NOI18N
        getContentPane().setLayout(null);

        usuario.setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().add(usuario);
        usuario.setBounds(240, 270, 170, 30);

        Usuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario:");
        getContentPane().add(Usuario);
        Usuario.setBounds(130, 270, 100, 22);

        Contrasena.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Contrasena.setForeground(new java.awt.Color(255, 255, 255));
        Contrasena.setText("Contraseña:");
        getContentPane().add(Contrasena);
        Contrasena.setBounds(100, 320, 130, 22);

        Ingresa.setBackground(new java.awt.Color(102, 0, 255));
        Ingresa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Ingresa.setText("Ingresa");
        Ingresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresaActionPerformed(evt);
            }
        });
        getContentPane().add(Ingresa);
        Ingresa.setBounds(30, 390, 110, 31);

        Inscribete.setBackground(new java.awt.Color(153, 255, 102));
        Inscribete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Inscribete.setText("Inscríbete");
        Inscribete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribeteActionPerformed(evt);
            }
        });
        getContentPane().add(Inscribete);
        Inscribete.setBounds(200, 390, 130, 31);

        Salir.setBackground(new java.awt.Color(102, 0, 255));
        Salir.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(360, 390, 80, 31);

        jPasswordField1.setBackground(new java.awt.Color(153, 153, 255));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(240, 320, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendavirtual/Barateroprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 40, 300, 180);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiendavirtual/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 500);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InscribeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribeteActionPerformed
          objeto1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_InscribeteActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Icon icono = new ImageIcon(getClass().getResource("baratero3.gif"));
        int opc;
         opc=JOptionPane.showOptionDialog(null, "Esta seguro que desea abandonar la página" ,null , WIDTH, WIDTH, icono,new Object[]{"SI" , "N0"} , null);
         if(opc==0){
            System.exit(0);
         }
        
        
         // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void IngresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresaActionPerformed

            
          // TODO add your handling code here:
        DatosUsuario oUsuario;
        oUsuario = DatosUsuario.getDatosUsuario();
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        //DatosListaProductos oListaProductos;
        //oListaProductos = DatosListaProductos.getListaProductos();
        
        String Usuario;
        String Password;
        
        
        Usuario = usuario.getText();
        Password = jPasswordField1.getText();
        Icon icono = new ImageIcon(getClass().getResource("baratero3.gif"));
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conexion = DriverManager.getConnection ("jdbc:mysql://localhost:3306/virtualtienda?zeroDateTimeBehavior=convertToNull","root", "");
            Statement s = conexion.createStatement();
            ResultSet rs = s.executeQuery ("select * from usuario WHERE Nombre = \""+Usuario+"\"AND password = \"" +Password+"\"");
            
            rs.last();
            if(rs.getRow()!=0){
                 rs.first();
                 oUsuario.setIdUsuario(rs.getInt(1));
                 oUsuario.setNombre(rs.getString(2));
                 oUsuario.setApellido(rs.getString(3));
                 oUsuario.setTelefono(rs.getString(4));
                 oUsuario.setEmail(rs.getString(5));
                 oUsuario.setPassword(rs.getString(7));
                 //Ingresa objeto2= new Ingresa();
                 IngresaMercadoLibre objeto2= new IngresaMercadoLibre();
                 objeto2.setVisible(true);
                 usuario.setText("");
                 jPasswordField1.setText("");
                 //System.out.println (rs.getInt (1) + " " + rs.getString (2)+ " "); 
            }
            else {
                JOptionPane.showMessageDialog(null, "Contraseña No Valida",null,WIDTH,icono);
                jPasswordField1.setText("");
                //Principal.regresa();
            }
            
             
        conexion.close();
        } catch (ClassNotFoundException | SQLException e)
        {
        }
        
            
    }//GEN-LAST:event_IngresaActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new PaginaPrincipal().setVisible(true);
            
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contrasena;
    private javax.swing.JButton Ingresa;
    private javax.swing.JButton Inscribete;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
